version: 2.1
orbs:
  jira: circleci/jira@1.2.2
workflows:
  version: 2
  test:
    jobs:
      - submit:
          context: pip-staging

jobs:
  submit:
    docker:
      - image: python:3.8
#    machine: true
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install --use-feature=2020-resolver duckietown-shell
            dts --set-version daffy
            dts update
      - run:
          name: Setup token
          command: |
            dts tok verify $token_dt1_bea
            dts tok set $token_dt1_bea

      - run:
          name: "Challenges info"
          command: |
            dts challenges info

      - run:
          name: Submit
          command: |
            make submit-bea
      - jira/notify
